name: CheckEsLint

on: 
  push:
    branches:
      - '**'
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies and Check Lint
        run: |
          npm install
          npm run lint
      env:
        CI: true